# Generated by Django 4.1.7 on 2023-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='User Paste', max_length=150)),
                ('author', models.CharField(default='Anonymous', max_length=150)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='text', max_length=150)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='', max_length=150)),
            ],
        ),
    ]
